"""Phase 1 updates

Revision ID: 68079f4cd0f0
Revises: a6761f0e6de0
Create Date: 2026-06-29 02:00:21.840290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68079f4cd0f0'
down_revision: Union[str, None] = 'a6761f0e6de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('orders', sa.Column('shipping_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('active_ingredient', sa.String(), nullable=True))
    op.add_column('products', sa.Column('contraindications', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('dosage', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'dosage')
    op.drop_column('products', 'contraindications')
    op.drop_column('products', 'active_ingredient')
    op.drop_column('products', 'category_id')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'note')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'shipping_address')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
